name: engez
description: "A new Flutter project."
publish_to: 'Skepr'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hijri: ^3.0.0
  intl: ^0.20.2
  battery_plus: ^6.2.1
  shared_preferences: ^2.5.2
  adhan: ^2.0.0+1
  url_launcher: ^6.3.1
  external_app_launcher: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Misans
      fonts:
        - asset: assets/fonts/شاومي.otf
          style: normal
